### ISSUE TITLE
Expanded Support

### ISSUE THREAD

**Issue by kudit** [sampettersson/Placement#13]
Has there been any consideration to expanding support to other SwiftUI platforms such as watchOS or tvOS?  I have some base restructuring code that even makes projects easily maintainable and editable from Swift Playgrounds on iPad if you'd be interested.

**Comment by sampettersson** [comment]
Yes, absolutely. Don't see why this shouldn't work on those platforms, unless they are missing some APIs. Mostly haven't tried or given it much thought.
