### ISSUE TITLE
Incorrect Defaults

### ISSUE THREAD

**Issue by Jaron-Lowe** [sampettersson/Placement#5]
[replacingUnspecifiedDimensions(by:)](https://developer.apple.com/documentation/swiftui/proposedviewsize/replacingunspecifieddimensions(by:)?changes=_3)

A default parameter exists for replacingUnspecifiedDimensions(by:) that is not in Placement. 

[updateCache(_:subviews:)](https://developer.apple.com/documentation/swiftui/layout/updatecache(_:subviews:)-9hkj9)

The default implementation of updateCache(_ cache: subviews:) should call makeCache.

Both issues are fixed in this [PR](https://github.com/sampettersson/Placement/pull/4)

**Comment by sampettersson** [comment]
Merged your PR so closing this now :)
